name: lint

on:
  push:
    branches:
      - feature

defaults:
  run:
    working-directory: ./hitorikura_shiru

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2

      - name: Cache composer
        id: cache
        uses: actions/cache@v2
        with:
          path: ./vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Composer install
        id: composer-install
        if: steps.cache.outputs.cache-hit != 'true'
        run: composer install -n --prefer-dist

      - name: Run larastan
        run: ./vendor/bin/phpstan analyse --configuration=phpstan.neon

      - name: Run php-cs-fixer
        run: ./vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php --verbose --dry-run || true
